<?php
$kratz_slider_sc = kratz_get_theme_option( 'front_page_title_shortcode' );
if ( ! empty( $kratz_slider_sc ) && strpos( $kratz_slider_sc, '[' ) !== false && strpos( $kratz_slider_sc, ']' ) !== false ) {

	?><div class="front_page_section front_page_section_title front_page_section_slider front_page_section_title_slider">
	<?php
		// Add anchor
		$kratz_anchor_icon = kratz_get_theme_option( 'front_page_title_anchor_icon' );
		$kratz_anchor_text = kratz_get_theme_option( 'front_page_title_anchor_text' );
	if ( ( ! empty( $kratz_anchor_icon ) || ! empty( $kratz_anchor_text ) ) && shortcode_exists( 'trx_sc_anchor' ) ) {
		echo do_shortcode(
			'[trx_sc_anchor id="front_page_section_title"'
									. ( ! empty( $kratz_anchor_icon ) ? ' icon="' . esc_attr( $kratz_anchor_icon ) . '"' : '' )
									. ( ! empty( $kratz_anchor_text ) ? ' title="' . esc_attr( $kratz_anchor_text ) . '"' : '' )
									. ']'
		);
	}
		// Show slider (or any other content, generated by shortcode)
		echo do_shortcode( $kratz_slider_sc );
	?>
	</div>
	<?php

} else {

	?>
	<div class="front_page_section front_page_section_title
		<?php
		$kratz_scheme = kratz_get_theme_option( 'front_page_title_scheme' );
		if ( ! empty( $kratz_scheme ) && ! kratz_is_inherit( $kratz_scheme ) ) {
			echo ' scheme_' . esc_attr( $kratz_scheme );
		}
		echo ' front_page_section_paddings_' . esc_attr( kratz_get_theme_option( 'front_page_title_paddings' ) );
		?>
		"
		<?php
		$kratz_css      = '';
		$kratz_bg_image = kratz_get_theme_option( 'front_page_title_bg_image' );
		if ( ! empty( $kratz_bg_image ) ) {
			$kratz_css .= 'background-image: url(' . esc_url( kratz_get_attachment_url( $kratz_bg_image ) ) . ');';
		}
		if ( ! empty( $kratz_css ) ) {
			echo ' style="' . esc_attr( $kratz_css ) . '"';
		}
		?>
	>
	<?php
		// Add anchor
		$kratz_anchor_icon = kratz_get_theme_option( 'front_page_title_anchor_icon' );
		$kratz_anchor_text = kratz_get_theme_option( 'front_page_title_anchor_text' );
	if ( ( ! empty( $kratz_anchor_icon ) || ! empty( $kratz_anchor_text ) ) && shortcode_exists( 'trx_sc_anchor' ) ) {
		echo do_shortcode(
			'[trx_sc_anchor id="front_page_section_title"'
									. ( ! empty( $kratz_anchor_icon ) ? ' icon="' . esc_attr( $kratz_anchor_icon ) . '"' : '' )
									. ( ! empty( $kratz_anchor_text ) ? ' title="' . esc_attr( $kratz_anchor_text ) . '"' : '' )
									. ']'
		);
	}
	?>
		<div class="front_page_section_inner front_page_section_title_inner
		<?php
		if ( kratz_get_theme_option( 'front_page_title_fullheight' ) ) {
			echo ' kratz-full-height sc_layouts_flex sc_layouts_columns_middle';
		}
		?>
			"
			<?php
			$kratz_css      = '';
			$kratz_bg_mask  = kratz_get_theme_option( 'front_page_title_bg_mask' );
			$kratz_bg_color_type = kratz_get_theme_option( 'front_page_title_bg_color_type' );
			if ( 'custom' == $kratz_bg_color_type ) {
				$kratz_bg_color = kratz_get_theme_option( 'front_page_title_bg_color' );
			} elseif ( 'scheme_bg_color' == $kratz_bg_color_type ) {
				$kratz_bg_color = kratz_get_scheme_color( 'bg_color', $kratz_scheme );
			} else {
				$kratz_bg_color = '';
			}
			if ( ! empty( $kratz_bg_color ) && $kratz_bg_mask > 0 ) {
				$kratz_css .= 'background-color: ' . esc_attr(
					1 == $kratz_bg_mask ? $kratz_bg_color : kratz_hex2rgba( $kratz_bg_color, $kratz_bg_mask )
				) . ';';
			}
			if ( ! empty( $kratz_css ) ) {
				echo ' style="' . esc_attr( $kratz_css ) . '"';
			}
			?>
		>
			<div class="front_page_section_content_wrap front_page_section_title_content_wrap content_wrap">
				<?php
				// Caption
				$kratz_caption = kratz_get_theme_option( 'front_page_title_caption' );
				if ( ! empty( $kratz_caption ) || ( current_user_can( 'edit_theme_options' ) && is_customize_preview() ) ) {
					?>
					<h1 class="front_page_section_caption front_page_section_title_caption front_page_block_<?php echo ! empty( $kratz_caption ) ? 'filled' : 'empty'; ?>"><?php echo wp_kses( $kratz_caption, 'kratz_kses_content' ); ?></h1>
					<?php
				}

				// Description (text)
				$kratz_description = kratz_get_theme_option( 'front_page_title_description' );
				if ( ! empty( $kratz_description ) || ( current_user_can( 'edit_theme_options' ) && is_customize_preview() ) ) {
					?>
					<div class="front_page_section_description front_page_section_title_description front_page_block_<?php echo ! empty( $kratz_description ) ? 'filled' : 'empty'; ?>"><?php echo wp_kses( wpautop( $kratz_description ), 'kratz_kses_content' ); ?></div>
					<?php
				}

				// Buttons
				if ( kratz_get_theme_option( 'front_page_title_button1_link' ) != '' || kratz_get_theme_option( 'front_page_title_button2_link' ) != '' ) {
					?>
					<div class="front_page_section_buttons front_page_section_title_buttons">
					<?php
						kratz_show_layout( kratz_customizer_partial_refresh_front_page_title_button1_link() );
						kratz_show_layout( kratz_customizer_partial_refresh_front_page_title_button2_link() );
					?>
					</div>
					<?php
				}
				?>
			</div>
		</div>
	</div>
	<?php
}
